name: E2E test

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
jobs:
  build:
    uses: 10up/safe-redirect-manager/.github/workflows/build-release-zip.yml@develop
  cypress:
    needs: build
    name: ${{ matrix.core.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#5.7'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download build zip
      uses: actions/download-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - name: Install dependencies
      run: npm install
    - name: Set the core version and plugins config
      run: ./tests/bin/set-wp-config.js --core=${{ matrix.core.version }} --plugins=./${{ github.event.repository.name }}
    - name: Set up WP environment
      run: npm run env:start
    - name: Test
      run: npm run cypress:run
    - name: Update summary
      if: always()
      run: |
          npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
          rm -rf ./tests/cypress/reports/mochawesome-*.json
          npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
          npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
          cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY
    - name: Make artifacts available
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-artifact
        retention-days: 2
        path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
            ${{ github.workspace }}/tests/cypress/reports/
